# Generated by Django 4.2.2 on 2023-10-11 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asosiy', '0002_mijoz_maxsulot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ombor',
            options={},
        ),
        migrations.AlterModelManagers(
            name='ombor',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='ombor',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='ombor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ombor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='ombor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='ombor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ombor',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='ombor',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='ombor',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='ombor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='ombor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='ombor',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='ombor',
            name='username',
        ),
        migrations.AddField(
            model_name='ombor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maxsulot',
            name='ombor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.ombor'),
        ),
        migrations.AlterField(
            model_name='mijoz',
            name='ombor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.ombor'),
        ),
    ]
