# Generated by Django 4.2.2 on 2023-10-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_alter_ombor_options_alter_ombor_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mijoz',
            name='qarz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
