# Generated by Django 4.2.2 on 2023-10-11 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asosiy', '0003_alter_ombor_options_alter_ombor_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('miqdor', models.PositiveIntegerField()),
                ('summa', models.PositiveIntegerField()),
                ('tolangan_summa', models.PositiveIntegerField()),
                ('maxsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.maxsulot')),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.mijoz')),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.ombor')),
            ],
        ),
    ]
